# Generated by Django 2.0.2 on 2018-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='filename_pattern',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
