# Generated by Django 2.0.2 on 2018-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_publication_filename_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'File Uploader')]),
        ),
    ]
