# Generated by Django 2.0.2 on 2018-03-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_publication_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
