# Generated by Django 2.0.2 on 2018-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20180425_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], max_length=10, null=True),
        ),
    ]
