# Generated by Django 2.0.2 on 2018-05-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20180502_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='code',
        ),
    ]
