# Generated by Django 2.0.2 on 2018-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_publisher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishermembership',
            name='is_contact',
            field=models.BooleanField(default=False, help_text='Designates if this member of the publisher should be considered as a contact or not.'),
        ),
        migrations.AlterField(
            model_name='publishermembership',
            name='is_primary_contact',
            field=models.BooleanField(default=False, help_text="If a contract doesn't have a contact user set the member with this flag will be used for invoice contact details."),
        ),
    ]
