# Generated by Django 2.0.5 on 2018-06-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_publicationconfigrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='salutation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
