# Generated by Django 2.0.2 on 2018-02-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_serviceevent_originator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
