# Generated by Django 2.0.2 on 2018-02-13 08:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_service_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
