# Generated by Django 2.0.2 on 2018-02-13 10:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_service_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='secure_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
