# Generated by Django 2.0.2 on 2018-02-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_service_secure_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='filename_pattern',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
