# Generated by Django 2.0.2 on 2018-02-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_service_filename_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.IntegerField(choices=[(0, 'SFTP'), (1, 'AboDB')], default=0),
            preserve_default=False,
        ),
    ]
