# Generated by Django 2.0.2 on 2018-02-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_membership_role'),
        ('status', '0008_auto_20180215_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Publication'),
        ),
        migrations.AddField(
            model_name='fileevent',
            name='severity',
            field=models.IntegerField(choices=[(0, 'Info'), (10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Critical')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileevent',
            name='subject',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='publication',
            field=models.ManyToManyField(blank=True, to='portal.Publication'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='severity',
            field=models.IntegerField(choices=[(0, 'Info'), (10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Critical')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='subject',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Success'), (1, 'In progress'), (2, 'Error')]),
        ),
    ]
