# Generated by Django 2.0.2 on 2018-02-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_auto_20180227_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-edition_date',)},
        ),
        migrations.AlterModelOptions(
            name='fileevent',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='serviceevent',
            options={'ordering': ('-timestamp',)},
        ),
    ]
