# Generated by Django 2.0.2 on 2018-03-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0011_auto_20180228_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-edition_date', '-updated_at', '-created_at')},
        ),
    ]
