# Generated by Django 2.0.2 on 2018-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_service_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.IntegerField(choices=[(0, 'Edition'), (1, 'Subscriptions')], default=0),
            preserve_default=False,
        ),
    ]
