# Generated by Django 2.0.2 on 2018-03-23 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0014_file_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_channel', models.IntegerField(choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Publication')])),
                ('notification_type', models.IntegerField(choices=[(0, 'Email'), (1, 'SMS')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fileevent',
            name='channel',
            field=models.IntegerField(blank=True, choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Publication')], null=True),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='channel',
            field=models.IntegerField(blank=True, choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Publication')], null=True),
        ),
    ]
