# Generated by Django 2.0.2 on 2018-03-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0015_auto_20180323_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileevent',
            name='channel',
            field=models.IntegerField(blank=True, choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Edition published')], null=True),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='event_channel',
            field=models.IntegerField(choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Edition published')]),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='channel',
            field=models.IntegerField(blank=True, choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Edition published')], null=True),
        ),
    ]
