# Generated by Django 2.0.2 on 2018-05-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0017_auto_20180327_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileevent',
            name='channel',
            field=models.IntegerField(blank=True, choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Edition published'), (4, 'Schedule missed')], null=True),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='event_channel',
            field=models.IntegerField(choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Edition published'), (4, 'Schedule missed')]),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='channel',
            field=models.IntegerField(blank=True, choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Edition published'), (4, 'Schedule missed')], null=True),
        ),
    ]
