# Generated by Django 2.0.2 on 2018-05-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20180508_1539'),
        ('status', '0019_auto_20180521_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Success'), (1, 'In progress'), (2, 'Error')])),
                ('severity', models.IntegerField(choices=[(0, 'Info'), (10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Critical')])),
                ('channel', models.IntegerField(blank=True, choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Edition published'), (4, 'Schedule missed')], null=True)),
                ('subject', models.CharField(default='', max_length=160, null=True)),
                ('details', models.TextField(default='', max_length=160, null=True)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Publication')),
            ],
            options={
                'ordering': ('-timestamp',),
                'abstract': False,
            },
        ),
    ]
