# Generated by Django 2.0.5 on 2018-06-08 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscription',
            name='severity',
            field=models.IntegerField(blank=True, choices=[(0, 'Info'), (10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Critical')], help_text='Notify about severity level equal or higher than this. Blank sends out notification regardless of severity level.', null=True),
        ),
        migrations.AddField(
            model_name='notificationsubscription',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Success'), (1, 'In progress'), (2, 'Error')], help_text='Notify about status level equal or higher than this. Blank sends out notification regardless of status level.', null=True),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'SMS')], help_text='How to send the notification out.'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
