# Generated by Django 2.0.5 on 2018-06-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_publicationconfigrule'),
        ('status', '0021_auto_20180608_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-edition__date', '-updated_at', '-created_at')},
        ),
        migrations.RemoveField(
            model_name='file',
            name='edition_date',
        ),
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Edition'), (1, 'Subscriptions')]),
        ),
        migrations.AddField(
            model_name='edition',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.File'),
        ),
        migrations.AddField(
            model_name='edition',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Publication'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('publication', 'date')},
        ),
    ]
