# Generated by Django 2.0.5 on 2018-06-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0022_auto_20180614_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Success'), (1, 'In progress'), (2, 'Error')])),
                ('severity', models.IntegerField(choices=[(0, 'Info'), (10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Critical')])),
                ('channel', models.IntegerField(blank=True, choices=[(0, 'File Upload'), (1, 'File Processing'), (2, 'User input needed'), (3, 'Edition published'), (4, 'Schedule missed')], null=True)),
                ('edition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.Edition')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Schedule')),
            ],
            options={
                'ordering': ('-timestamp',),
                'abstract': False,
            },
        ),
    ]
