# Generated by Django 2.0.2 on 2018-05-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0010_auto_20180502_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdfusionContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField()),
                ('deactivation_date', models.DateField(blank=True, null=True)),
                ('processing_fee', models.FloatField()),
                ('monthly_base_fee', models.FloatField(blank=True, null=True)),
                ('nonrevenue_discount_pct', models.FloatField(blank=True, help_text='Discount for processing of non-revenue ads. Applied as a percentage to all ads. Decimal value in range [0-100]', null=True, verbose_name='Ads non-revenue discount percentage')),
                ('general_discount_pct', models.FloatField(blank=True, help_text='Discount percentage applied to all billed AdFusion items. Decimal value in range [0-100]', null=True, verbose_name='General discount percentage')),
                ('billed_ads', models.CharField(choices=[('published_revenue', 'Only published ads with revenue'), ('all', 'All ads')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publications', models.ManyToManyField(to='portal.Publication')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adfusion_contract', to='portal.Publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdFusionInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_base_fee', models.FloatField(blank=True, null=True)),
                ('processing_fee', models.FloatField(default=0)),
                ('ad_count', models.PositiveIntegerField(default=0)),
                ('processing_total', models.FloatField(default=0)),
                ('nonrevenue_discount_pct', models.FloatField(blank=True, null=True)),
                ('nonrevenue_discount_total', models.FloatField(blank=True, null=True)),
                ('pre_general_discount_total', models.FloatField(default=0)),
                ('general_discount_pct', models.FloatField(blank=True, null=True)),
                ('general_discount_total', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdFusionInvoiceDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ad_count', models.PositiveIntegerField()),
                ('processing_total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adfusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='crm.AdFusionInvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('invoice_date', models.DateField()),
                ('invoice_start_date', models.DateField()),
                ('invoice_end_date', models.DateField()),
                ('invoice_due_date', models.DateField()),
                ('vat_number', models.CharField(max_length=255)),
                ('vat_pct', models.FloatField(blank=True, null=True)),
                ('vat_total', models.FloatField(blank=True, null=True)),
                ('pre_vat_total', models.FloatField(blank=True, null=True)),
                ('exact_total', models.FloatField(blank=True, null=True)),
                ('final_total', models.FloatField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('contact_full_name', models.CharField(max_length=255)),
                ('contact_billing_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(choices=[('adfusion', 'AdFusion'), ('newsfusion', 'NewsFusion')], max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('paid', 'Paid')], default='pending', max_length=255)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='portal.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='NewsfusionContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField()),
                ('deactivation_date', models.DateField(blank=True, null=True)),
                ('page_fee', models.FloatField()),
                ('discount_pct', models.FloatField(blank=True, null=True)),
                ('billed_pages', models.CharField(choices=[('per_page', 'All pages of edition.'), ('per_processed_page', 'Only news pages.')], max_length=30)),
                ('publications', models.ManyToManyField(to='portal.Publication')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsfusion_contract', to='portal.Publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsFusionInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_fee', models.FloatField(default=0)),
                ('pre_discount_total', models.FloatField(default=0)),
                ('discount_pct', models.FloatField(default=0)),
                ('discount_total', models.FloatField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsfusion', to='crm.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='NewsFusionInvoiceDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_count', models.PositiveIntegerField()),
                ('processing_total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('newsfusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='crm.NewsFusionInvoice')),
            ],
        ),
        migrations.AddField(
            model_name='adfusioninvoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adfusion', to='crm.Invoice'),
        ),
    ]
