# Generated by Django 2.0.5 on 2018-05-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_publicationconfigrule'),
        ('crm', '0004_auto_20180508_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='publications',
            field=models.ManyToManyField(related_name='invoices', to='portal.Publication'),
        ),
    ]
