# Generated by Django 2.0.5 on 2018-06-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_invoice_contact_salutation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adfusioninvoiceday',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='newsfusioninvoiceday',
            options={'ordering': ('date',)},
        ),
    ]
